# Generated by Django 6.0.1 on 2026-01-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="Email")),
                ("name", models.CharField(help_text="Введите Ф.И.О.", max_length=100, verbose_name="Ф.И.О.")),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="Введите комментарий", null=True, verbose_name="Комментарий"
                    ),
                ),
            ],
            options={
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылки",
                "ordering": ["name", "email"],
            },
        ),
    ]
